# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Wwk6C36tLJMOCk0C5L3hfEoxZ-HjZwy
"""

import pandas as pd
import statsmodels.api as sm
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score

def load_cleaned_data(file_path='cleaned_student_data.csv'):
    """Nạp dữ liệu đã qua xử lý từ file CSV"""
    try:
        df = pd.read_csv(file_path)
        print(f"--- Đã nạp dữ liệu từ {file_path} thành công ---")
        return df
    except FileNotFoundError:
        print("Lỗi: Không tìm thấy file dữ liệu. Vui lòng chạy file cleaning trước.")
        return None

def perform_causal_analysis(df):
    """Phân tích nhân quả bằng mô hình OLS trên toàn bộ tập dữ liệu"""
    print("\n" + "="*50)
    print("--- BẮT ĐẦU PHÂN TÍCH NHÂN QUẢ (CAUSAL ANALYSIS) ---")

    # Định nghĩa các đặc trưng cho phân tích nhân quả
    features_analysis = [
        'Academic_Burnout_Score',
        'Sleep_Hygiene_Risk',
        'Overall_Sleep_Quality',
        'Exercise_Frequency'
    ]

    X = df[features_analysis]
    y = df['Academic_Stress_Level']

    # Thêm hằng số (intercept) cho OLS
    X_with_const = sm.add_constant(X)

    # Huấn luyện mô hình
    ols_analysis_model = sm.OLS(y, X_with_const).fit()

    print("\nBảng hệ số tác động (Coefficients) - Hướng và Độ mạnh:")
    print(ols_analysis_model.params.sort_values(ascending=False))

    print("\nChi tiết bảng báo cáo thống kê:")
    print(ols_analysis_model.summary())
    print("="*50)
    return ols_analysis_model

def train_predictive_models(df):
    """Huấn luyện và so sánh mô hình OLS Baseline với Random Forest tối ưu"""
    print("\n--- BẮT ĐẦU HUẤN LUYỆN MÔ HÌNH DỰ BÁO ---")

    # 1. Định nghĩa tập đặc trưng (đầy đủ hơn cho dự báo)
    features_model = [
        'Academic_Burnout_Score',
        'Sleep_Hygiene_Risk',
        'Overall_Sleep_Quality',
        'Exercise_Frequency',
        'GPA_Rating',
        'Sleep_Hours_Total'
    ]

    X = df[features_model]
    y = df['Academic_Stress_Level']

    # 2. Chia tập dữ liệu (80% Train, 20% Test)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # 3. Baseline OLS Model
    X_train_ols = sm.add_constant(X_train)
    X_test_ols = sm.add_constant(X_test)
    ols_model = sm.OLS(y_train, X_train_ols).fit()
    y_pred_ols = ols_model.predict(X_test_ols)

    # 4. Optimized Random Forest Regressor
    rf_optimized = RandomForestRegressor(
        n_estimators=100,
        max_depth=5,
        min_samples_leaf=10,
        random_state=42
    )
    rf_optimized.fit(X_train, y_train)
    y_pred_rf = rf_optimized.predict(X_test)

    # 5. Đánh giá hiệu suất
    print("\n--- Kết quả OLS Baseline (Test Set) ---")
    print(f"R-squared: {r2_score(y_test, y_pred_ols):.3f}")
    print(f"MAE: {mean_absolute_error(y_test, y_pred_ols):.3f}")

    print("\n--- Kết quả Optimized Random Forest (Test Set) ---")
    print(f"R-squared: {r2_score(y_test, y_pred_rf):.3f}")
    print(f"MAE: {mean_absolute_error(y_test, y_pred_rf):.3f}")

    return rf_optimized, features_model

if __name__ == "__main__":
    # Bước 1: Load dữ liệu
    df_clean = load_cleaned_data('Student_Mental_Health_Final.csv')

    if df_clean is not None:
        # Bước 2: Phân tích nhân quả (Analysis)
        perform_causal_analysis(df_clean)

        # Bước 3: Huấn luyện mô hình dự báo (Modeling)
        rf_model, features = train_predictive_models(df_clean)

        # Bước 4: Lưu kết quả dự báo cuối cùng vào dataframe (tùy chọn)
        df_clean['Stress_Predicted'] = rf_model.predict(df_clean[features])
        df_clean.to_csv('Student_Mental_Health_Predictions.csv', index=False)
        print("\n--- Đã lưu kết quả dự báo vào file 'Student_Mental_Health_Predictions.csv' ---")